CREATE TABLE IF NOT EXISTS GENRE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT GENRE_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MPA (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(10) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(200),
    CONSTRAINT MPA_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS "USER" (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(60) NOT NULL,
    LOGIN VARCHAR(60) NOT NULL UNIQUE,
    EMAIL VARCHAR(200) NOT NULL UNIQUE,
    BIRTHDAY DATE NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS FILM (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(200),
    RELEASE_DATE DATE NOT NULL,
    DURATION INTEGER NOT NULL CHECK (DURATION > 0),
    MPA_ID INTEGER NOT NULL,
    CONSTRAINT FILM_PK PRIMARY KEY (ID),
    CONSTRAINT FILM_MPA_FK FOREIGN KEY (MPA_ID) REFERENCES MPA(ID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS FILM_GENRE (
    FILM_ID INTEGER NOT NULL,
    GENRE_ID INTEGER NOT NULL,
    CONSTRAINT FILM_GENRE_PK PRIMARY KEY (FILM_ID, GENRE_ID),
    CONSTRAINT FILM_FK FOREIGN KEY (FILM_ID) REFERENCES FILM(ID) ON DELETE CASCADE,
    CONSTRAINT GENRE_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FILM_LIKE (
    FILM_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT FILM_LIKE_PK PRIMARY KEY (FILM_ID, USER_ID),
    CONSTRAINT LIKE_FILM_FK FOREIGN KEY (FILM_ID) REFERENCES FILM(ID) ON DELETE CASCADE,
    CONSTRAINT LIKE_USER_FK FOREIGN KEY (USER_ID) REFERENCES "USER"(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FRIENDSHIP (
    USER_ID INTEGER NOT NULL,
    FRIEND_ID INTEGER NOT NULL,
    STATUS BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT FRIENDSHIP_PK PRIMARY KEY (USER_ID, FRIEND_ID),
    CONSTRAINT FRIENDSHIP_USER_FK FOREIGN KEY (USER_ID) REFERENCES "USER"(ID) ON DELETE CASCADE,
    CONSTRAINT FRIENDSHIP_FRIEND_FK FOREIGN KEY (FRIEND_ID) REFERENCES "USER"(ID) ON DELETE CASCADE
);